### ISSUE TITLE
두 compose.yml  파일 중 하난 잘 되고 하난 nginx가 뜹니다.

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [beyond-sw-camp/be01-101#47]
```
$ dokcer -v 
Docker version 25.0.1, build 29cf629
```

## nginx 뜨는 compose.yml
```
version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "7777:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  blog:
    # build: ../../docker_file/httpd
    image: memento12/testblog-a:0.1.0
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=naver.apple.com
      - VIRTUAL_PORT=80
```
